# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\srtm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Form_Gis(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1085, 623)
        self.label_main_map = QtWidgets.QLabel(Dialog)
        self.label_main_map.setGeometry(QtCore.QRect(450, 40, 591, 491))
        self.label_main_map.setObjectName("label_main_map")
        self.pushButton_load_map = QtWidgets.QPushButton(Dialog)
        self.pushButton_load_map.setGeometry(QtCore.QRect(30, 20, 171, 31))
        self.pushButton_load_map.setObjectName("pushButton_load_map")
        self.pushButton_show_grafic = QtWidgets.QPushButton(Dialog)
        self.pushButton_show_grafic.setGeometry(QtCore.QRect(30, 290, 171, 31))
        self.pushButton_show_grafic.setObjectName("pushButton_show_grafic")
        self.pushButton_close_program = QtWidgets.QPushButton(Dialog)
        self.pushButton_close_program.setGeometry(QtCore.QRect(30, 540, 171, 31))
        self.pushButton_close_program.setObjectName("pushButton_close_program")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 120, 371, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_point_1 = QtWidgets.QLabel(self.widget)
        self.label_point_1.setObjectName("label_point_1")
        self.verticalLayout.addWidget(self.label_point_1)
        self.label_point_2 = QtWidgets.QLabel(self.widget)
        self.label_point_2.setObjectName("label_point_2")
        self.verticalLayout.addWidget(self.label_point_2)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(20, 340, 351, 111))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_distanse = QtWidgets.QLabel(self.widget1)
        self.label_distanse.setObjectName("label_distanse")
        self.verticalLayout_2.addWidget(self.label_distanse)
        self.label_rasrechinie = QtWidgets.QLabel(self.widget1)
        self.label_rasrechinie.setObjectName("label_rasrechinie")
        self.verticalLayout_2.addWidget(self.label_rasrechinie)
        self.label_size_of_map = QtWidgets.QLabel(self.widget1)
        self.label_size_of_map.setObjectName("label_size_of_map")
        self.verticalLayout_2.addWidget(self.label_size_of_map)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_main_map.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_load_map.setText(_translate("Dialog", "Загрузить карту"))
        self.pushButton_show_grafic.setText(_translate("Dialog", "Отобразить график"))
        self.pushButton_close_program.setText(_translate("Dialog", "Закрыть программу"))
        self.label_point_1.setText(_translate("Dialog", "TextLabel"))
        self.label_point_2.setText(_translate("Dialog", "TextLabel"))
        self.label_distanse.setText(_translate("Dialog", "TextLabel"))
        self.label_rasrechinie.setText(_translate("Dialog", "TextLabel"))
        self.label_size_of_map.setText(_translate("Dialog", "TextLabel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    first_part = QtWidgets.QDialog()
    ui = Form_Gis()
    ui.setupUi(first_part)
    first_part.show()
    sys.exit(app.exec_())